### ISSUE TITLE
not really an issue but we need a hotkey to activate

### ISSUE THREAD

**Issue by Vaashx** [TheG-VAN/dwm_frame_interpolator#2]
like the title said it would be nice if we can get a keybind/hotkey to activate it easily, and btw your DWM frame interpolator is very good now you are competing against losslesscaling in my opinion and not gonna lie you are very good so yeah it would be on the top to have a hotkey with a possibilty when it's activated to clip the cursor on the window/games for it help since it really interpolate when it's in fullscreen windowed or only windowed because ingame it's not working in fullscreen exclusive, keep going, go to the TOP !

**Comment by TheG-VAN** [comment]
Hi, thanks for the kind words!

I will add a hotkey to enable/disable the interpolator.

Unfortunately, it won't be possible to make the interpolator work for fullscreen exclusive. This is because the interpolation is done on the Desktop Window Manager (DWM). This is a Windows application which manages visual effects (like transparency) on the desktop. The frame interpolator basically hijacks this application to run an interpolation shader on the desktop. However, since the purpose of DWM is for the desktop, it is doesn't run on top of fullscreen exclusive games.

**Comment by Vaashx** [comment]
ok i understand

**Comment by TheG-VAN** [comment]
Hotkey has been added
